{
 "title": "Clash dashboard",
 "description": "Clash exporter example dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "source",
    "query": "label_values(clash_network_traffic_bytes_total, source)"
   },
   {
    "name": "policy",
    "label": "policy",
    "query": "label_values(clash_network_traffic_bytes_total, policy)"
   },
   {
    "name": "type",
    "label": "type",
    "query": "label_values(clash_network_traffic_bytes_total, type)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "版本",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max (clash_info) by (version, premium)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总下载量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clash_download_bytes_total" }
   ]
  },
  {
   "title": "总上传量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clash_upload_bytes_total" }
   ]
  },
  {
   "title": "连接数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clash_active_connections" }
   ]
  },
  {
   "title": "实时网速",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(clash_network_traffic_bytes_total{type=\"download\"}[30s]))",
     "legendFormat": "download"
    },
    {
     "expr": "sum(rate(clash_network_traffic_bytes_total{type=\"upload\"}[1m]))",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "客户端总流量",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum by (source) (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\", type=~\"$type\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "代理总流量",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum by (policy) (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\", type=~\"$type\"}[$__range]))",
     "legendFormat": "来源"
    }
   ]
  },
  {
   "title": "目的地总流量",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum by (destination) (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[$__range]))))",
     "legendFormat": "来源"
    }
   ]
  },
  { "title": "Traffic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "策略流量统计",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (policy) (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (policy) (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[3h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (policy) (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[6h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (policy) (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[1d]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (policy) (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "客户端流量统计",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (source) (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (source) (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[3h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (source) (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[6h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (source) (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[1d]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (source) (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}